#############################################################################
# Makefile for building: posAppQT
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 2? 15 20:51:21 2022
# Project:  Signals.pro
# Template: app
# Command: /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/qmake -spec /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile Signals.pro
#############################################################################

####### Compiler, tools and options

CC            = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/arm-buildroot-linux-gnueabihf-gcc
CXX           = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/arm-buildroot-linux-gnueabihf-g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -std=gnu++98 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ -I. -I/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtCore -I/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtNetwork -I/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtGui -I/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtSql -I/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include -I. -I. -I. -I.
LINK          = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/arm-buildroot-linux-gnueabihf-g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -L/usr/lib -lasound -L/mnt/hgfs/V3SPOS/qt/pos/DK_YKT-QT-V3S-master/./ - lQtSql-lsqlite3 -L/mnt/hgfs/V3SPOS/qt/pos/DK_YKT-QT-V3S-master/./ -lreadcard -L/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot//usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/arm-buildroot-linux-gnueabihf-ar cqs
RANLIB        = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/arm-buildroot-linux-gnueabihf-ranlib
QMAKE         = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/arm-buildroot-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cJSON.c \
		mainwindow.cpp \
		modifysystimeui.cpp \
		setup.cpp \
		ipinformation.cpp \
		devmsg.cpp \
		setconsumemode.cpp \
		queryconsumerecord.cpp \
		querydayconsumemoney.cpp \
		dialog.cpp \
		mainconsumeinterface.cpp \
		sqlite3Qt.cpp moc_dialog.cpp \
		moc_mainwindow.cpp \
		moc_modifysystimeui.cpp \
		moc_setup.cpp \
		moc_ipinformation.cpp \
		moc_devmsg.cpp \
		moc_setconsumemode.cpp \
		moc_queryconsumerecord.cpp \
		moc_querydayconsumemoney.cpp \
		moc_mainconsumeinterface.cpp
OBJECTS       = main.o \
		cJSON.o \
		mainwindow.o \
		modifysystimeui.o \
		setup.o \
		ipinformation.o \
		devmsg.o \
		setconsumemode.o \
		queryconsumerecord.o \
		querydayconsumemoney.o \
		dialog.o \
		mainconsumeinterface.o \
		sqlite3Qt.o \
		moc_dialog.o \
		moc_mainwindow.o \
		moc_modifysystimeui.o \
		moc_setup.o \
		moc_ipinformation.o \
		moc_devmsg.o \
		moc_setconsumemode.o \
		moc_queryconsumerecord.o \
		moc_querydayconsumemoney.o \
		moc_mainconsumeinterface.o
DIST          = /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/unix.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/linux.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base-unix.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-base.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-unix.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/qws.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qconfig.pri \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_functions.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_config.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/exclusive_builds.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_pre.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/debug.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_post.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/shared.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/warn_on.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/unix/thread.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/moc.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/resources.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/uic.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/yacc.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/lex.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/include_source_dir.prf \
		Signals.pro
QMAKE_TARGET  = posAppQT
DESTDIR       = 
TARGET        = posAppQT

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainconsumewindow.h ui_mainwindow.h ui_setup.h ui_ipinformation.h ui_devmsg.h ui_setconsumemode.h ui_queryconsumerecord.h ui_querydayconsumemoney.h ui_dialog.h ui_mainconsumeinterface.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Signals.pro  /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++/qmake.conf /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/unix.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/linux.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base-unix.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-base.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-unix.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/qws.conf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qconfig.pri \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_functions.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_config.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/exclusive_builds.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_pre.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/debug.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_post.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/shared.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/warn_on.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/unix/thread.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/moc.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/resources.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/uic.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/yacc.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/lex.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/include_source_dir.prf \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtSql.prl \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtCore.prl \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtGui.prl \
		/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtNetwork.prl
	$(QMAKE) -spec /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile Signals.pro
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/unix.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/linux.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base-unix.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-base.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-unix.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/qws.conf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qconfig.pri:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_functions.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_config.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/exclusive_builds.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_pre.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/debug.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_post.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/shared.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/warn_on.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/unix/thread.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/moc.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/resources.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/uic.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/yacc.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/lex.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/include_source_dir.prf:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtSql.prl:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtCore.prl:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtGui.prl:
/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ CONFIG+=debug -o Makefile Signals.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/posAppQT1.0.0 || $(MKDIR) .tmp/posAppQT1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/posAppQT1.0.0/ && $(COPY_FILE) --parents dialog.h mainwindow.h modifysystimeui.h setup.h ipinformation.h sqlite3.h devmsg.h setconsumemode.h queryconsumerecord.h querydayconsumemoney.h mainconsumeinterface.h sqlite3Qt.h .tmp/posAppQT1.0.0/ && $(COPY_FILE) --parents main.cpp cJSON.c mainwindow.cpp modifysystimeui.cpp setup.cpp ipinformation.cpp devmsg.cpp setconsumemode.cpp queryconsumerecord.cpp querydayconsumemoney.cpp dialog.cpp mainconsumeinterface.cpp sqlite3Qt.cpp .tmp/posAppQT1.0.0/ && $(COPY_FILE) --parents mainconsumewindow.ui mainwindow.ui setup.ui ipinformation.ui devmsg.ui setconsumemode.ui queryconsumerecord.ui querydayconsumemoney.ui dialog.ui mainconsumeinterface.ui .tmp/posAppQT1.0.0/ && (cd `dirname .tmp/posAppQT1.0.0` && $(TAR) posAppQT1.0.0.tar posAppQT1.0.0 && $(COMPRESS) posAppQT1.0.0.tar) && $(MOVE) `dirname .tmp/posAppQT1.0.0`/posAppQT1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/posAppQT1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp moc_mainwindow.cpp moc_modifysystimeui.cpp moc_setup.cpp moc_ipinformation.cpp moc_devmsg.cpp moc_setconsumemode.cpp moc_queryconsumerecord.cpp moc_querydayconsumemoney.cpp moc_mainconsumeinterface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_mainwindow.cpp moc_modifysystimeui.cpp moc_setup.cpp moc_ipinformation.cpp moc_devmsg.cpp moc_setconsumemode.cpp moc_queryconsumerecord.cpp moc_querydayconsumemoney.cpp moc_mainconsumeinterface.cpp
moc_dialog.cpp: dialog.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_mainwindow.cpp: dialog.h \
		sqlite3.h \
		setconsumemode.h \
		mainconsumeinterface.h \
		mainwindow.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_modifysystimeui.cpp: sqlite3.h \
		modifysystimeui.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) modifysystimeui.h -o moc_modifysystimeui.cpp

moc_setup.cpp: setup.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) setup.h -o moc_setup.cpp

moc_ipinformation.cpp: sqlite3.h \
		ipinformation.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) ipinformation.h -o moc_ipinformation.cpp

moc_devmsg.cpp: sqlite3.h \
		devmsg.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) devmsg.h -o moc_devmsg.cpp

moc_setconsumemode.cpp: sqlite3.h \
		mainconsumeinterface.h \
		setconsumemode.h \
		setconsumemode.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) setconsumemode.h -o moc_setconsumemode.cpp

moc_queryconsumerecord.cpp: sqlite3.h \
		queryconsumerecord.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) queryconsumerecord.h -o moc_queryconsumerecord.cpp

moc_querydayconsumemoney.cpp: sqlite3.h \
		querydayconsumemoney.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) querydayconsumemoney.h -o moc_querydayconsumemoney.cpp

moc_mainconsumeinterface.cpp: sqlite3.h \
		setconsumemode.h \
		mainconsumeinterface.h \
		mainconsumeinterface.h
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/moc $(DEFINES) $(INCPATH) mainconsumeinterface.h -o moc_mainconsumeinterface.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainconsumewindow.h ui_mainwindow.h ui_setup.h ui_ipinformation.h ui_devmsg.h ui_setconsumemode.h ui_queryconsumerecord.h ui_querydayconsumemoney.h ui_dialog.h ui_mainconsumeinterface.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainconsumewindow.h ui_mainwindow.h ui_setup.h ui_ipinformation.h ui_devmsg.h ui_setconsumemode.h ui_queryconsumerecord.h ui_querydayconsumemoney.h ui_dialog.h ui_mainconsumeinterface.h
ui_mainconsumewindow.h: mainconsumewindow.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic mainconsumewindow.ui -o ui_mainconsumewindow.h

ui_mainwindow.h: mainwindow.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_setup.h: setup.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic setup.ui -o ui_setup.h

ui_ipinformation.h: ipinformation.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic ipinformation.ui -o ui_ipinformation.h

ui_devmsg.h: devmsg.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic devmsg.ui -o ui_devmsg.h

ui_setconsumemode.h: setconsumemode.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic setconsumemode.ui -o ui_setconsumemode.h

ui_queryconsumerecord.h: queryconsumerecord.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic queryconsumerecord.ui -o ui_queryconsumerecord.h

ui_querydayconsumemoney.h: querydayconsumemoney.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic querydayconsumemoney.ui -o ui_querydayconsumemoney.h

ui_dialog.h: dialog.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic dialog.ui -o ui_dialog.h

ui_mainconsumeinterface.h: mainconsumeinterface.ui
	/media/user1/V3SSDK_BUILDROOT/v3ssdk/buildroot/out/host/bin/uic mainconsumeinterface.ui -o ui_mainconsumeinterface.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ipinformation.h \
		sqlite3.h \
		setup.h \
		devmsg.h \
		setconsumemode.h \
		mainconsumeinterface.h \
		queryconsumerecord.h \
		querydayconsumemoney.h \
		modifysystimeui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cJSON.o: cJSON.c cJSON.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cJSON.o cJSON.c

mainwindow.o: mainwindow.cpp mainwindow.h \
		dialog.h \
		sqlite3.h \
		setconsumemode.h \
		mainconsumeinterface.h \
		ui_mainwindow.h \
		sqlite3QT.h \
		setup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

modifysystimeui.o: modifysystimeui.cpp modifysystimeui.h \
		sqlite3.h \
		ui_modifysystimeui.h \
		setup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modifysystimeui.o modifysystimeui.cpp

setup.o: setup.cpp setup.h \
		ui_setup.h \
		setconsumemode.h \
		sqlite3.h \
		mainconsumeinterface.h \
		ipinformation.h \
		querydayconsumemoney.h \
		queryconsumerecord.h \
		devmsg.h \
		sqlite3QT.h \
		modifysystimeui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setup.o setup.cpp

ipinformation.o: ipinformation.cpp ipinformation.h \
		sqlite3.h \
		ui_ipinformation.h \
		setup.h \
		sqlite3QT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipinformation.o ipinformation.cpp

devmsg.o: devmsg.cpp devmsg.h \
		sqlite3.h \
		ui_devmsg.h \
		setup.h \
		sqlite3QT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o devmsg.o devmsg.cpp

setconsumemode.o: setconsumemode.cpp setconsumemode.h \
		sqlite3.h \
		mainconsumeinterface.h \
		ui_setconsumemode.h \
		setup.h \
		sqlite3QT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setconsumemode.o setconsumemode.cpp

queryconsumerecord.o: queryconsumerecord.cpp queryconsumerecord.h \
		sqlite3.h \
		ui_queryconsumerecord.h \
		setup.h \
		sqlite3QT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryconsumerecord.o queryconsumerecord.cpp

querydayconsumemoney.o: querydayconsumemoney.cpp querydayconsumemoney.h \
		sqlite3.h \
		ui_querydayconsumemoney.h \
		setup.h \
		sqlite3QT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o querydayconsumemoney.o querydayconsumemoney.cpp

dialog.o: dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

mainconsumeinterface.o: mainconsumeinterface.cpp mainconsumeinterface.h \
		sqlite3.h \
		setconsumemode.h \
		ui_mainconsumeinterface.h \
		cJSON.h \
		sqlite3QT.h \
		setup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainconsumeinterface.o mainconsumeinterface.cpp

sqlite3Qt.o: sqlite3Qt.cpp sqlite3.h \
		sqlite3QT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlite3Qt.o sqlite3Qt.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_modifysystimeui.o: moc_modifysystimeui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modifysystimeui.o moc_modifysystimeui.cpp

moc_setup.o: moc_setup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setup.o moc_setup.cpp

moc_ipinformation.o: moc_ipinformation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ipinformation.o moc_ipinformation.cpp

moc_devmsg.o: moc_devmsg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_devmsg.o moc_devmsg.cpp

moc_setconsumemode.o: moc_setconsumemode.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setconsumemode.o moc_setconsumemode.cpp

moc_queryconsumerecord.o: moc_queryconsumerecord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_queryconsumerecord.o moc_queryconsumerecord.cpp

moc_querydayconsumemoney.o: moc_querydayconsumemoney.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_querydayconsumemoney.o moc_querydayconsumemoney.cpp

moc_mainconsumeinterface.o: moc_mainconsumeinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainconsumeinterface.o moc_mainconsumeinterface.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

